include_guard(GLOBAL)

macro(nerve_configure_x86_simd_support)
    set(NERVE_TARGET_SUPPORTS_X86_SIMD OFF)
    if(CMAKE_OSX_ARCHITECTURES)
        set(NERVE_TARGET_SUPPORTS_X86_SIMD ON)
        foreach(NERVE_OSX_ARCH IN LISTS CMAKE_OSX_ARCHITECTURES)
            string(TOLOWER "${NERVE_OSX_ARCH}" NERVE_OSX_ARCH_LOWER)
            if(NOT NERVE_OSX_ARCH_LOWER MATCHES "^(x86_64|amd64|i[3-6]86)$")
                set(NERVE_TARGET_SUPPORTS_X86_SIMD OFF)
            endif()
        endforeach()
    else()
        string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" NERVE_SYSTEM_PROCESSOR_LOWER)
        if(NERVE_SYSTEM_PROCESSOR_LOWER MATCHES "^(x86_64|amd64|i[3-6]86)$")
            set(NERVE_TARGET_SUPPORTS_X86_SIMD ON)
        endif()
    endif()

    set(NERVE_CAN_USE_X86_SIMD_FLAGS OFF)
    if(NERVE_TARGET_SUPPORTS_X86_SIMD
       AND CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
        set(NERVE_CAN_USE_X86_SIMD_FLAGS ON)
    endif()
endmacro()

macro(nerve_detect_avx512_codegen)
    if(NOT DEFINED NERVE_CAN_USE_X86_SIMD_FLAGS)
        nerve_configure_x86_simd_support()
    endif()

    if(NERVE_CAN_USE_X86_SIMD_FLAGS)
        include(CheckCXXSourceCompiles)
        include(CheckCXXSourceRuns)
        set(NERVE_SAVED_CMAKE_REQUIRED_FLAGS "${CMAKE_REQUIRED_FLAGS}")
        set(CMAKE_REQUIRED_FLAGS "-mavx512f")
        check_cxx_source_compiles("#include <immintrin.h>\nint main() { __m512i a; return 0; }" NERVE_HAS_AVX512)
        if(NERVE_HAS_AVX512 AND NOT CMAKE_CROSSCOMPILING)
            check_cxx_source_runs("#include <immintrin.h>\nint main() { __m512i a = _mm512_set1_epi32(1); return _mm512_cvtsi512_si32(a) == 1 ? 0 : 1; }" NERVE_HAS_AVX512_RUNTIME)
        elseif(NERVE_HAS_AVX512)
            set(NERVE_HAS_AVX512_RUNTIME UNKNOWN)
        else()
            set(NERVE_HAS_AVX512_RUNTIME OFF)
        endif()
        set(CMAKE_REQUIRED_FLAGS "${NERVE_SAVED_CMAKE_REQUIRED_FLAGS}")
        if(NERVE_HAS_AVX512)
            if(NERVE_HAS_AVX512_RUNTIME)
                message(STATUS "AVX-512 codegen and runtime execution are available")
            elseif(NERVE_HAS_AVX512_RUNTIME STREQUAL "UNKNOWN")
                message(STATUS "AVX-512 codegen is available; runtime execution was not checked while cross-compiling")
            else()
                message(STATUS "AVX-512 codegen is available, but this CPU cannot execute AVX-512 instructions")
            endif()
        else()
            message(STATUS "AVX-512 codegen missing - Building AVX-512 kernels out")
        endif()
    else()
        set(NERVE_HAS_AVX512 OFF)
        if(NERVE_TARGET_SUPPORTS_X86_SIMD)
            message(STATUS "AVX-512 detection skipped - Unsupported compiler")
        else()
            message(STATUS "AVX-512 detection skipped - Non-x86 target architecture")
        endif()
    endif()
endmacro()

macro(nerve_validate_simd_mode)
    set(NERVE_SIMD "auto" CACHE STRING "SIMD mode: auto|avx2|avx512|scalar")
    set_property(CACHE NERVE_SIMD PROPERTY STRINGS auto avx2 avx512 scalar)

    if(NOT DEFINED NERVE_CAN_USE_X86_SIMD_FLAGS)
        nerve_configure_x86_simd_support()
    endif()
    if(NOT DEFINED NERVE_HAS_AVX512)
        nerve_detect_avx512_codegen()
    endif()

    set(NERVE_ENABLE_AVX512_CODEGEN OFF)
    if(NERVE_SIMD STREQUAL "avx2")
        if(NOT NERVE_CAN_USE_X86_SIMD_FLAGS)
            message(FATAL_ERROR "NERVE_SIMD=avx2 requires an x86/x86_64 target and a GNU/Clang-compatible compiler")
        endif()
    elseif(NERVE_SIMD STREQUAL "avx512")
        if(NOT NERVE_CAN_USE_X86_SIMD_FLAGS)
            message(FATAL_ERROR "NERVE_SIMD=avx512 requires an x86/x86_64 target and a GNU/Clang-compatible compiler")
        endif()
        if(NOT NERVE_HAS_AVX512)
            message(FATAL_ERROR "NERVE_SIMD=avx512 was requested, but the compiler does not accept AVX-512 codegen flags")
        endif()
        if(NOT CMAKE_CROSSCOMPILING AND NOT NERVE_HAS_AVX512_RUNTIME)
            if(DEFINED NERVE_SKIP_AVX512_RUNTIME_CHECK AND NERVE_SKIP_AVX512_RUNTIME_CHECK)
                message(WARNING "NERVE_SIMD=avx512: CPU cannot execute AVX-512 instructions (runtime check skipped via NERVE_SKIP_AVX512_RUNTIME_CHECK)")
            else()
                message(FATAL_ERROR "NERVE_SIMD=avx512 was requested, but this CPU cannot execute AVX-512 instructions")
            endif()
        endif()
        set(NERVE_ENABLE_AVX512_CODEGEN ON)
    elseif(NERVE_SIMD STREQUAL "auto" OR NERVE_SIMD STREQUAL "scalar")
        # Auto and scalar builds keep target-safe compiler flags.
    else()
        message(FATAL_ERROR "NERVE_SIMD must be auto, avx2, avx512, or scalar")
    endif()
endmacro()

function(nerve_apply_simd target)
    set(NERVE_SIMD_VISIBILITY PRIVATE)
    if(ARGC GREATER 1)
        set(NERVE_SIMD_VISIBILITY "${ARGV1}")
    endif()

    if(NOT DEFINED NERVE_CAN_USE_X86_SIMD_FLAGS)
        nerve_configure_x86_simd_support()
    endif()
    if(NOT DEFINED NERVE_ENABLE_AVX512_CODEGEN)
        nerve_validate_simd_mode()
    endif()

    if(NERVE_SIMD STREQUAL "scalar")
        target_compile_definitions(${target} ${NERVE_SIMD_VISIBILITY} NERVE_SIMD_FORCE_SCALAR)
    elseif(NERVE_SIMD STREQUAL "avx2")
        target_compile_definitions(${target} ${NERVE_SIMD_VISIBILITY} NERVE_SIMD_FORCE_AVX2)
        target_compile_options(${target} ${NERVE_SIMD_VISIBILITY}
            "$<$<COMPILE_LANGUAGE:CXX>:-mavx2;-mfma>"
        )
    elseif(NERVE_SIMD STREQUAL "avx512")
        target_compile_definitions(${target} ${NERVE_SIMD_VISIBILITY} NERVE_SIMD_FORCE_AVX512)
        target_compile_options(${target} ${NERVE_SIMD_VISIBILITY}
            "$<$<COMPILE_LANGUAGE:CXX>:-mavx512f;-mfma>"
        )
    elseif(NERVE_SIMD STREQUAL "auto")
        target_compile_definitions(${target} ${NERVE_SIMD_VISIBILITY} NERVE_SIMD_AUTO)
    else()
        message(FATAL_ERROR "NERVE_SIMD must be auto, avx2, avx512, or scalar")
    endif()
endfunction()
